POST http://localhost:3001/api/notes/
Content-Type: application/json

{
        "userId": 1,
        "title": "Segundo Tema",
        "body": "Frontend whit React",
        "important": true
}

###

POST http://localhost:3001/api/notes/
Content-Type: application/json

{

}

###

# Este archivo Se usa para documentar la API-REST
# Con la extencion "Rest Client"
# Se usan ### tres almoadillas para separar una de otra